### ISSUE TITLE
Need NPM release?

### ISSUE THREAD

**Issue by lucacorti** [devotox/ember-paper-input-mask#4]
I noticed 2.0.1 is tagged and contains the notifyPropertyChange fixes, however npm still lists 1.0.14 as the current release.

Can this be released? Also you may want to add ember-notify-property-change-polyfill to dependencies to maintain compatibility with ember < 3.1.

https://emberjs.com/deprecations/v3.x/#toc_use-notifypropertychange-instead-of-propertywillchange-and-propertydidchange

**Comment by devotox** [comment]
sorry about this but there has been a change from paper-input-mask to ember-paper-input-mask and you would need to use the new NPM name @lucacorti
